# SPDX-License-Identifier: GPL-2.0
#
# This file should be included by external modules that need to link to this
# project.

KCFLAGS += -I$(ROOT_DIR)/private/google-modules/soc/gs/include
KCFLAGS += -I$(ROOT_DIR)/private/google-modules/soc/gs/include/uapi

ifneq ($(wildcard $(COMMON_OUT_DIR)/private/google-modules/soc/gs/Module.symvers),)
EXTRA_SYMBOLS += $(COMMON_OUT_DIR)/private/google-modules/soc/gs/Module.symvers
endif
