# SPDX-License-Identifier: GPL-2.0-or-later

load("@kleaf//build/kernel/kleaf:kernel.bzl", "ddk_module", "kernel_module_group")

filegroup(
    name = "gsa.kconfig",
    srcs = [
        "Kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_module(
    name = "gsa_ko",
    srcs = glob([
        "**/*.h",
    ]),
    out = "gsa.ko",
    conditional_srcs = {
        "CONFIG_GSA": {
            True: [
                "gsa_core.c",
                "gsa_log.c",
                "gsa_tz.c",
            ],
        },
        "CONFIG_GSA_DEBUGFS": {
            True: [
                "gsa_debugfs.c",
            ],
        },
        "CONFIG_GSA_LEGACY_MAILBOX": {
            True: [
                "gsa_mbox_legacy.c",
            ],
        },
        "CONFIG_GSA_LINUX_MAILBOX": {
            True: [
                "gsa_mbox.c",
            ],
        },
    },
    copts = [
        "-Wno-missing-prototypes",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/aoc:__subpackages__",
        "//private/google-modules/edgetpu:__subpackages__",
        "//private/google-modules/gxp:__subpackages__",
        "//private/google-modules/trusty:__subpackages__",
    ],
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/trusty",
        "//private/google-modules/trusty:trusty_headers",
    ],
)

ddk_module(
    name = "gsa_gsc",
    srcs = glob([
        "**/*.h",
    ]) + [
        "gsa_gsc.c",
    ],
    out = "gsa_gsc.ko",
    copts = [
        "-Wno-missing-prototypes",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    deps = [
        ":gsa_ko",
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/trusty:trusty_headers",
    ],
)

ddk_module(
    name = "tzprot",
    srcs = glob([
        "**/*.h",
    ]) + [
        "tzprot.c",
    ],
    out = "tzprot.ko",
    copts = [
        "-Wno-missing-prototypes",
    ],
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/google-modules/display:__subpackages__",
    ],
    deps = [
        ":gsa_ko",
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/trusty:trusty_headers",
    ],
)

kernel_module_group(
    name = "gsa",
    srcs = [
        ":gsa_gsc",
        ":gsa_ko",
        ":tzprot",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_module(
    name = "gsa_core_kunit_test",
    srcs = [
        "gsa_core_test.c",
        "gsa_mbox.h",
        "gsa_priv.h",
        "gsa_tz.h",
        "mock_gsa_mbox.c",
        "mock_gsa_mbox.h",
    ],
    out = "gsa_kunit_test.ko",
    copts = [
        "-Wno-missing-prototypes",
    ],
    defconfig = "kunit_defconfig",
    kconfig = "Kconfig",
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
    deps = [
        ":gsa_gsc",
        ":gsa_ko",
        ":tzprot",
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
        "//private/google-modules/trusty:trusty_headers",
    ],
)

# Public headers are located at
# //private/google-modules/soc/gs:gs_soc_headers
